require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|
  config.ssh.username = "fedora"
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider "openstack" do |os|
    os.openstack_auth_url = "http://192.168.1.11:5000/v2.0"
    os.username = "labadmin"
    os.password = "redhat123"
    os.tenant_name = "starlabs"
    os.server_name = "vagrant-instance"
    os.flavor = "m1.small"
    os.image = "fedora-24"
    os.floating_ip_pool = "public"
    os.networks = "labnet01"
    os.keypair_name = "starlabs"
    os.security_groups = ["default","core_services"]
  end
end
